"""empty message

Revision ID: 92453e73a7a9
Revises: 82184d7d1e88
Create Date: 2018-04-21 19:19:25.704690

"""

# revision identifiers, used by Alembic.
revision = '92453e73a7a9'
down_revision = '82184d7d1e88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_team_member_team_id'), 'team_member', ['team_id', 'user_id'])
    op.drop_constraint('_team_user_uc', 'team_member', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_team_user_uc', 'team_member', ['team_id', 'user_id'])
    op.drop_constraint(op.f('uq_team_member_team_id'), 'team_member', type_='unique')
    # ### end Alembic commands ###
